source "https://rubygems.org"

gem "fluentd", "1.1.3"
gem "oj", "3.5.1"
gem "fluent-plugin-elasticsearch"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "fluent-plugin-genhashvalue"
gem "ffi"
gem "fluent-plugin-systemd"
